# Generated by Django 3.1.1 on 2020-12-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLClickHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nbapp.url')),
            ],
        ),
    ]
